// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfl2-Jecm8HTwtYCiU2Jy1D4hOkUBEfqo',
    appId: '1:943355302377:web:c3460f7caaece86636bb78',
    messagingSenderId: '943355302377',
    projectId: 'skin-agent-e82e1',
    authDomain: 'skin-agent-e82e1.firebaseapp.com',
    storageBucket: 'skin-agent-e82e1.firebasestorage.app',
    measurementId: 'G-Z2F0WP4NCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSlTRZ_K82sWW-093D_p-bvyy9VIIm6lI',
    appId: '1:943355302377:android:f136b8ac3936e79f36bb78',
    messagingSenderId: '943355302377',
    projectId: 'skin-agent-e82e1',
    storageBucket: 'skin-agent-e82e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrVRGeglJpYu4g2k6LnX4zgGpUPmABHo4',
    appId: '1:943355302377:ios:b2e7376618174a1f36bb78',
    messagingSenderId: '943355302377',
    projectId: 'skin-agent-e82e1',
    storageBucket: 'skin-agent-e82e1.firebasestorage.app',
    iosBundleId: 'com.example.claudeSkinOs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrVRGeglJpYu4g2k6LnX4zgGpUPmABHo4',
    appId: '1:943355302377:ios:b2e7376618174a1f36bb78',
    messagingSenderId: '943355302377',
    projectId: 'skin-agent-e82e1',
    storageBucket: 'skin-agent-e82e1.firebasestorage.app',
    iosBundleId: 'com.example.claudeSkinOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfl2-Jecm8HTwtYCiU2Jy1D4hOkUBEfqo',
    appId: '1:943355302377:web:a92ada26e842317536bb78',
    messagingSenderId: '943355302377',
    projectId: 'skin-agent-e82e1',
    authDomain: 'skin-agent-e82e1.firebaseapp.com',
    storageBucket: 'skin-agent-e82e1.firebasestorage.app',
    measurementId: 'G-QHX56F26JE',
  );
}
